### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by sebhahn**
- Update project files using pyscaffold v3.3
- Add github workflow
- Yapf code formatting

### CODE REVIEW

**Comment by sebhahn** [comment]
@cpaulik could you please make a new release if everything is fine

**Comment by cpaulik** [comment]
Thank you. Are you in a hurry? 

If not I'll probably check on Friday or early next week.

Also if you've already tested that this all works I'm happy to just merge. Just let me know.

**Comment by sebhahn** [comment]
Kind of, since the problem is that new conda environments can't be installed that depend on datedown. Updating to pyscaffold v3.3 should fix this issue. Otherwise datedown should work as intended.

```
  × Running setup.py install for datedown did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/datedown
      copying datedown/urlcreator.py -> build/lib/datedown
      copying datedown/dates.py -> build/lib/datedown
      copying datedown/down.py -> build/lib/datedown
      copying datedown/interface.py -> build/lib/datedown
      copying datedown/fname_creator.py -> build/lib/datedown
      copying datedown/__init__.py -> build/lib/datedown
      copying datedown/wget.py -> build/lib/datedown
      running egg_info
      writing datedown.egg-info/PKG-INFO
      writing dependency_links to datedown.egg-info/dependency_links.txt
      writing entry points to datedown.egg-info/entry_points.txt
      writing requirements to datedown.egg-info/requires.txt
      writing top-level names to datedown.egg-info/top_level.txt
      [pbr] Reusing existing SOURCES.txt
      running install_lib
      creating /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown
      copying build/lib/datedown/urlcreator.py -> /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown
      copying build/lib/datedown/dates.py -> /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown
      copying build/lib/datedown/down.py -> /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown
      copying build/lib/datedown/interface.py -> /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown
      copying build/lib/datedown/fname_creator.py -> /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown
      copying build/lib/datedown/__init__.py -> /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown
      copying build/lib/datedown/wget.py -> /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown
      byte-compiling /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown/urlcreator.py to urlcreator.cpython-38.pyc
      byte-compiling /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown/dates.py to dates.cpython-38.pyc
      byte-compiling /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown/down.py to down.cpython-38.pyc
      byte-compiling /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown/interface.py to interface.cpython-38.pyc
      byte-compiling /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown/fname_creator.py to fname_creator.cpython-38.pyc
      byte-compiling /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown/__init__.py to __init__.cpython-38.pyc
      byte-compiling /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown/wget.py to wget.cpython-38.pyc
      running install_egg_info
      Copying datedown.egg-info to /root/miniconda/envs/warp_h_nrt_env/lib/python3.8/site-packages/datedown-0.3-py3.8.egg-info
      running install_scripts
      error: invalid command 'bdist_wininst'
      [end of output]
```

**Comment by cpaulik** [comment]
Yes, we ran into the same issues recently - https://github.com/pypa/setuptools/issues/3525

I think pinning setuptools should solve the environment building issue. 
Anyway. I'll look at this now and release a new version later today

**Comment by cpaulik** [comment]
0.4 has been released and pushed to pypi

**Comment by sebhahn** [comment]
thanks!

**Pull request merged**
